# Generated by Django 5.1.7 on 2025-03-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0002_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
