# Generated by Django 5.1.7 on 2025-03-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0003_student_student_id_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=20),
        ),
    ]
