# Generated by Django 5.1.7 on 2025-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="dept_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "departmentName",
                    models.CharField(db_column="dept_name", max_length=100),
                ),
                (
                    "createAt",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("dept_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="emp_id", primary_key=True, serialize=False
                    ),
                ),
                ("firstName", models.CharField(db_column="first_name", max_length=100)),
                ("lastName", models.CharField(db_column="last_name", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phoneNumber", models.CharField(db_column="phone", max_length=15)),
                ("hireDate", models.DateField(db_column="hire_date")),
                ("salary", models.FloatField()),
                (
                    "createAt",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("salary", models.IntegerField()),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="hist_id", primary_key=True, serialize=False
                    ),
                ),
                ("oldSalary", models.FloatField(db_column="old_salary")),
                ("salary", models.FloatField(db_column="new_salary")),
                ("changeDate", models.DateField(db_column="changed_at")),
                ("changedBy", models.CharField(db_column="changed_by", max_length=100)),
            ],
            options={
                "db_table": "salary_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryHistorys",
            fields=[
                ("hist_id", models.IntegerField(primary_key=True, serialize=False)),
                ("old_salary", models.IntegerField()),
                ("new_salary", models.IntegerField()),
                ("changed_at", models.DateTimeField()),
                ("changed_by", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "salary_history",
                "managed": False,
            },
        ),
    ]
