# Generated by Django 5.1.7 on 2025-04-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_chart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.IntegerField(
                        db_column="dept_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(blank=True, db_column="dept_name", max_length=100),
                ),
                ("dept_level", models.IntegerField(db_column="dept_level")),
            ],
            options={
                "db_table": "dept_test",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="dept_test",
        ),
    ]
