# Generated by Django 5.1.7 on 2025-03-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={"managed": False},
        ),
    ]
